framework:
    #esi:             ~
    translator:      { fallback: en }
    serializer:      { enable_annotations: true }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:
        { enabled: true }
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    #trusted_proxies: ~ #Removed, see UPGRADE-3.3.md
    session:         ~
    fragments:       ~
    http_method_override: true
    assets:          ~
