imports:
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: partkeepr.yml }
    - { resource: config_framework.yml }
    - { resource: config_doctrine.yml }
    - { resource: config_fos_user.yml }
    - { resource: config_partkeepr.yml }
    - { resource: config_filesystem.yml }
    - { resource: config_apiplatform.yml}

sensio_framework_extra:
    view:    { annotations: true }
    router:  { annotations: true }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ PartKeeprFrontendBundle, PartKeeprMobileFrontendBundle ]
    filters:
        cssrewrite: ~

#Exception controllers removed from FOSRest..Will figure this out later.
#twig:
#    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'


sprite_generator:
    sprites:
        fugue16:
            inDir: %kernel.root_dir%/../vendor/brainbits/fugue-icons-bundle/src/Brainbits/FugueIconsBundle/Resources/public/icons/fugue/16/
            outImage: %kernel.root_dir%/../web/spritesheets/fugue-16.png
            outCss: %kernel.root_dir%/../web/spritesheets/fugue-16.css
            relativeImagePath: ./
            padding: 5
            spriteClass: fugue-icon
            cssFormat: css
            imagePositioning: min-image
            imageGenerator: gd2
        partkeepr:
            inDir: %kernel.root_dir%/../src/PartKeepr/FrontendBundle/Resources/public/images/icons/
            outImage: %kernel.root_dir%/../web/spritesheets/partkeepr.png
            outCss: %kernel.root_dir%/../web/spritesheets/partkeepr.css
            relativeImagePath: ./
            padding: 5
            spriteClass: partkeepr-icon
            cssFormat: css
            imagePositioning: min-image
            imageGenerator: gd2

services:
    partkeepr.exception_normalizer:
        class: PartKeepr\DoctrineReflectionBundle\Normalizer\ExceptionNormalizer
        tags:
            - { name: serializer.normalizer }


services:
    serializer.normalizer.custom:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            - "@serializer.mapping.class_metadata_factory"
            - null
            - "@serializer.property_accessor"
        tags:
            - { name: serializer.normalizer, priority: -1 }
        calls:
            - method: "setCircularReferenceLimit"
              arguments: [ [ 5 ] ]

